export const LIST_WORKFLOWS = 'LIST_WORKFLOWS';
export const ADD_WORKFLOW = 'ADD_WORKFLOW';
export const FILTER_WORKFLOW = 'FILTER_WORKFLOW';
export const DELETE_WORKFLOW = 'FILTER_WORKFLOW';
export const UPDATE_WORKFLOW = 'UPDATE_WORKFLOW';
export const SET_CURRENT_WORKFLOW = 'SET_CURRENT_WORKFLOW';
